spring:
  application:
    name: test-notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-group
logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
server:
  port: 8081
